name: Pack

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: josStorer/get-current-time@v2
        id: datetime
        with:
          format: YYYYMMDD

      - id: tagname
        run: echo "name=${{ steps.datetime.outputs.formattedTime }}_$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - uses: vimtor/action-zip@v1.1
        name: Pack prusaslicer
        with:
          files: PrusaSlicer/
          dest: prusaslicer-by-dylan_${{ steps.tagname.outputs.name }}.zip

      - uses: vimtor/action-zip@v1.1
        name: Pack orcaslicer
        with:
          files: OrcaSlicer/
          dest: orcaslicer-by-dylan_${{  steps.tagname.outputs.name  }}.zip

      - name: Create tag
        run: |
          git tag ${{ steps.tagname.outputs.name }}
          git push --tags

      - uses: softprops/action-gh-release@v1
        name: Create Release
        with:
          tag_name: ${{ steps.tagname.outputs.name }}
          prerelease: true
          files: ${{ github.workspace }}/*.zip

