name: Pack

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: josStorer/get-current-time@v2
        id: datetime
        with:
          format: YYYYMMDD

      - uses: vimtor/action-zip@v1.1
        name: Pack prusaslicer
        with:
          files: PrusaSlicer/
          dest: prusaslicer-by-dylan_${{ steps.datetime.outputs.time }}_${{ GITHUB_SHA::7 }}.zip

      - uses: vimtor/action-zip@v1.1
        name: Pack orcaslicer
        with:
          files: OrcaSlicer/
          dest: orcaslicer-by-dylan_${{ steps.datetime.outputs.time }}_${{ GITHUB_SHA::7 }}.zip

      - uses: softprops/action-gh-release@v1
        name: Create Release
        with:
          prerelease: true
          files: ${{ GITHUB_WORKSPACE }}/*.zip

