name: Pack

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: josStorer/get-current-time@v2
        id: datetime
        with:
          format: YYYYMMDD

      - uses: vimtor/action-zip@v1.1
        name: Pack prusaslicer
        with:
          files: PrusaSlicer/
          dest: prusaslicer-by-dylan_${{ steps.datetime.outputs.time }}_${{ github.sha::7 }}.zip

      - uses: vimtor/action-zip@v1.1
        name: Pack orcaslicer
        with:
          files: OrcaSlicer/
          dest: orcaslicer-by-dylan_${{ steps.datetime.outputs.time }}_${{ github.sha::7 }}.zip

      - uses: rickstaa/action-create-tag@v1
        id: tag_create
        with:
          tag: ${{ steps.datetime.outputs.formattedTime }}_${{ github.sha::7 }}
          tag_exists_error: false

      - uses: softprops/action-gh-release@v1
        name: Create Release
        with:
          tag_name: ${{ steps.datetime.outputs.formattedTime }}_${{ github.sha::7 }}
          prerelease: true
          files: ${{ github.workspace }}/*.zip

